# Generated by Django 4.0.5 on 2022-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Boeing AH-64 Apache')], max_length=1, null=True),
        ),
    ]
