# Generated by Django 4.0.5 on 2022-06-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-full_name',)},
        ),
    ]
